### ISSUE TITLE
[Feature] Provide time as argument

### ISSUE THREAD

**Issue by kalaschnik** [vitorgalvao/shutdown-timer-workflow#1]
### Workflow version

2023.3

### Alfred version

5.1.2

### macOS version

Ventura, 13.5 (22G74)

### Debugger output

```alfred_debugger
...
```

### More details

It would be great to provide a time via argument (e.g.,`shutdown 120s`, or `shutdown 1h`) for a timed shutdown.

**Comment by vitorgalvao** [comment]
Thank you for the request, but at this time I don’t intend to add a custom argument for shutdown. Especially if I were to interpret the hours/minutes/seconds as in my other workflows, that’d mean adding code to it and I like that the current iteration has zero code in it: it makes for a good learning resource in a moderately complex set up.
